clear all;
close all;

folder_path='C:\Data\dedalus';
slurm_list={'10249087'};
stress_list={'u_prime_u_prime',...
    'v_prime_v_prime',...
    'w_prime_w_prime',...
    'u_prime_v_prime',...
    'u_prime_T_prime',...
    'v_prime_T_prime',...
    'w_prime_T_prime'};
stress_label_list={'$\langle u''u''\rangle $',...
    '$\langle v''v''\rangle$',...
    '$\langle w''w''\rangle$',...
    '$\langle u''v''\rangle$',...
    '$\langle u''T''\rangle$',...
    '$\langle v''T''\rangle$',...
    '$\langle w''T''\rangle$'};
average_range=[500,1000];

for slurm_ind=1:length(slurm_list)
    % data{slurm_ind}.y=squeeze(h5read([folder_path,'\dedalus_',slurm_list{slurm_ind},'\snapshots_channel_stress\snapshots_channel_stress_s1.h5'],['/scales/']));
    h5name=[folder_path,'\dedalus_',slurm_list{slurm_ind},'\snapshots_channel_stress\snapshots_channel_stress_s1.h5'];
    for stress_ind=1:length(stress_list)
        data{slurm_ind}.(stress_list{stress_ind})=squeeze(h5read(h5name,['/tasks/',stress_list{stress_ind}]));
        data{slurm_ind}.y=h5read(h5name,'/scales/y_hash_04efb45f3573dba433867d7f01cfa48347d433e5');
    
        data_plot{1}.x=data{slurm_ind}.y;
        data_plot{1}.y=mean(data{slurm_ind}.(stress_list{stress_ind})(:,average_range),2); 
        plot_config.label_list={1,'y',stress_label_list{stress_ind}}; 
        plot_config.name=[stress_list{stress_ind},'.png'];
        plot_line(data_plot,plot_config);
    end
    
end